// <auto-generated />
using System;
using BookingRoomCampus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingRoomCampus.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212151643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BookingRoomCampus.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JamMulai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JamSelesai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
